<a href="https://colab.research.google.com/github/zupandit/pyTorchLearning/blob/main/00_pytorch_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.2.1+cu121


In [ ]:
#scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [ ]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [3,5]])
MATRIX
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[1,2,3]]]
)
TENSOR.shape

torch.Size([1, 2, 3])

In [ ]:
vector = torch.tensor([[1,2,3],
                       [4,5,6]])
vector.shape

torch.Size([2, 3])

In [ ]:
#Random Tensors
RAND_TENSOR = torch.rand(1,2,3)
RAND_TENSOR


tensor([[[0.4561, 0.8049, 0.0392],
         [0.3941, 0.9171, 0.3499]]])

In [ ]:
#Zero tensors
ZERO_TENSOR = torch.zeros(3,1)
ZERO_TENSOR

tensor([[0.],
        [0.],
        [0.]])

In [ ]:
#ONES tensors
ONE_T = torch.ones(size=(3,3))
ONE_T

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#You can essentially do some masking with these:

#For eg I have my one and zero tensors. Lets multiply them and see the result
ONE_T*ZERO_TENSOR

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#Creating numbers in a range
one_ten = torch.arange(1,11)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zero_thousand_100 = torch.arange(start=0,end=1001, step=100)
zero_thousand_100

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
#Creating tensors that are LIKE other tensors
zero_like = torch.zeros_like(input=one_ten)
zero_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Float 32 tensor
float_32_TENSOR = torch.tensor([1.0])
float_32_TENSOR.dtype

torch.float32

In [ ]:
float_16_TENSOR = float_32_TENSOR.type(torch.half)
float_16_TENSOR

tensor([1.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand((2,3), dtype=torch.float16)
some_tensor

tensor([[0.2988, 0.6631, 0.6597],
        [0.1338, 0.0723, 0.9824]], dtype=torch.float16)

In [ ]:
mat1 = torch.tensor([1,2,3])
mat2 = torch.tensor([1,1,1])
print(mat1.shape)

mat3 = torch.matmul(mat1, mat2)
mat3

torch.Size([3])


tensor(6)

In [ ]:
#So for matrix mul obv the columns of the first matrix and the rows of the second matrix
# must be the same. The dimension of the resulting matrix will be the rows of the mat1 and
# columns of mat2.

#This is why:
mat1 @ mat2
# works even though the 1*3 and 1*3 matrices should technically not work.
# They work because if we do tensor.shape we get 3 for both of them therefore
# as per torch's rules they can be multiplied

#but
# torch.rand(1,2)@ torch.rand(3,2) will not work
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 3x2)

#Normal matrix multiplication works fine
t3 = torch.rand(1,2)@torch.rand(2,1)
print(t3)
t3.shape

# and the resulting shape is 1*1



tensor([[0.2950]])


torch.Size([1, 1])

In [ ]:
# Tensors of shape 3.2 and 3.2 cannot be multiplied
# but if we transpose one of them, we get 3.2 and 2.3 which should work

tensor_A = torch.tensor([[1,2],
            [1,2],
            [1,2]])

tensor_B = torch.tensor([[2,3],
            [2,3],
            [2,3]])

tensor_A

# tensor_A @ tensor_B --> this gives an error
tensor_A_transpose = tensor_A.T

tensor_A_transpose@tensor_B

# tensor.T ; the T gives us the transpose

tensor([[ 6,  9],
        [12, 18]])

In [3]:
#Tensor aggregation. Finding things like min max mean sum etc
X = torch.arange(0,100,10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
#Min:
min = X.amin()
min
max = X.amax()
max

tensor(90)

In [11]:
#mean
torch.mean(X.type(torch.float32))

tensor(45.)

In [12]:
#Sum
torch.sum(X)

tensor(450)

In [31]:
%%time
min = X.min()
min_index = (X == min).nonzero(as_tuple = True)[0]
min_index

#The above code converts tensor to a boolean tensor where only indices at which the
# value is equal to min are set to true. Next we use .nonzero() to only get the true indices
# in a tuiple since true = 1. And at last,we return the first index

CPU times: user 251 µs, sys: 8 µs, total: 259 µs
Wall time: 264 µs


tensor([0])

In [34]:
#Alternatively we can use something like arg min
min_index_arg = X.argmin()
min_index_arg

max_index = X.argmax()
max_index

tensor(9)

In [36]:
y = torch.arange(1., 10.)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
#Reshaping the tensor
y_reshaped = y.reshape(1,9) #This added an extra y dimension to our tensor
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [39]:
# y_reshaped_2 = y.reshape(2,9)
# y_reshaped_2
# This gives an error^
# we only have 9 elements so how can we make an 18 element tensor

# On the other hand we can do of shape 9*1 since we do have 9 elements
y_reshaped_2 = y.reshape(9,1)
y_reshaped_2

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [42]:
#We can reshaope a tensor in any way as long as no. of elements are not changed
ten_tensor = torch.arange(1.0, 11.0)
ten_tensor
ten_tensor_reshape = ten_tensor.reshape(5,2)
ten_tensor_reshaped_otherway = ten_tensor.reshape(2,5)
print(ten_tensor_reshape)
print(ten_tensor_reshaped_otherway)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])


In [9]:
#We can change change the view of a tensor and store the new
# way to view the tensor in a different variable. But they will still refer to
# same tensor. So if the tensor in memory is changed, both the tensors
# will change

x = torch.arange(1.,11.,1)
# print(x)
y = x.view(2,5)
# print(y)
#Now if we change y
y[0][0] = 11.0
print(y)
print(x)
#Just changing y changed both x and y

tensor([[11.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [15]:
#In stacking, I think dimension lets up specify on which dimension
# should stacking happen. When dim=0, we stack on x axis and so on
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked
# I think h stack is stack but dim = 1 and v stack is dim =0

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [38]:
#Squeeze removes dimensions of size 1 from specified axis
# for e.g. the first dimension from the left side here
# is deleted
x = torch.zeros(1,1,2,1,2)
y = torch.squeeze(x,0)
print(y.size())

#now lets delete from the 2-nd last aka y axis
y = torch.squeeze(x,3)
print(y.shape)

# Doing something like (x,4) would not do anything since on the 4th aka x axis
# the dimension has more than 1 element

rand_tensor = torch.tensor([[[1,2,3],
                  [4,5,6]]])
print(rand_tensor.squeeze(0).shape)

# rand_tensor_mod = rand_tensor.squeeze()

#Unsqueeze does the opposite by adding a dimension of size 1 at specified pos.
tensor_unsqueeze = torch.tensor([1,2,3])
tensor_unsqueezed = torch.unsqueeze(tensor_unsqueeze,0)
print(tensor_unsqueezed)
#clearly, the tensor_unqueezed has an extra y dimension



torch.Size([1, 2, 1, 2])
torch.Size([1, 1, 2, 2])
torch.Size([2, 3])
tensor([[1, 2, 3]])


In [3]:
#Permute: allows you to specify where to put the
# dimensions of a tensor at. For e.g you can swap a 3*2 tensor to 2*3

x = torch.rand(3,2)
print(x.shape)
x_permuted = x.permute(1,0)
print(x_permuted.shape)

#Keep in mind permute just changes the view. So, y references the same tensor as
# x in memory


torch.Size([3, 2])
torch.Size([2, 3])


In [4]:
#Indexing in multi dim tensors
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [6]:
print(x[0]) #Z indexing
print(x[0][0]) # Y
print(x[0][0][0]) # X

# Lets get the 2nd element from the 3rd y axis in the first z axis. Should be 8
print(x[0,2,1]) # Same as x[0][2][1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(8)


In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
# In indexing we can get all values from a specific index using :
x = torch.arange(1,10).reshape(1,3,3)
print(x)
#All values from z and y dim but only middle ones from x
print(x[:, :, 1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[2, 5, 8]])


In [11]:
#All values of 0 dim but only 1 from all others
print(x[:,1,1])

tensor([5])


In [13]:
print(x[0,2,2])
print(x[:,:,2] )

tensor(9)
tensor([[3, 6, 9]])


In [17]:
#PyTorch tensors and NumPy
# Data in NumpPy to PyTorch tensor -> torch.from_numpy(ndarray)
# reverse is torch.Tensor.numpy()
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: numpy default dtype is float64
print(array, tensor)
print(tensor.type(torch.float32).dtype)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
torch.float32


In [18]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [19]:
numpy_tensor.dtype

dtype('float32')

In [31]:
import torch

random_t_a = torch.rand(3,4)
random_t_b = torch.rand(3,4)

print(random_t_a)
print(random_t_b)
print(random_t_a == random_t_b)

tensor([[0.0687, 0.7665, 0.6895, 0.6511],
        [0.0719, 0.2570, 0.1989, 0.9765],
        [0.3727, 0.4607, 0.3294, 0.0876]])
tensor([[0.0109, 0.3948, 0.7693, 0.6673],
        [0.5468, 0.0698, 0.7967, 0.2384],
        [0.0828, 0.9779, 0.1112, 0.6267]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [37]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)


print(random_tensor_d == random_tensor_c)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
##Running tensors and pytorch objects on GPUs (faster computation)

!nvidia-smi

Tue May 21 09:12:11 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
#Check GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [3]:
#Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [5]:
# Putting tensors and models on the GPU
tensor = torch.tensor([1,2,3], device='cpu')

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
#Moving back to CPU
tensor_on_cpu = tensor.to('cpu')
tensor_on_cpu, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [12]:
# We cant use numpy with gpu tensors
tensor_on_gpu = tensor.to(device)
# numpyArray = tensor_on_gpu.numpy()TypeError: can't convert cuda:0 device type
#  tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

numpyArray = tensor_on_gpu.cpu().numpy()
print(numpyArray)
tensor_on_gpu

[1 2 3]


tensor([1, 2, 3], device='cuda:0')