<a href="https://colab.research.google.com/github/zupandit/pyTorchLearning/blob/main/00_pytorch_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.2.1+cu121


In [ ]:
#scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [ ]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [3,5]])
MATRIX
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[1,2,3]]]
)
TENSOR.shape

torch.Size([1, 2, 3])

In [ ]:
vector = torch.tensor([[1,2,3],
                       [4,5,6]])
vector.shape

torch.Size([2, 3])

In [ ]:
#Random Tensors
RAND_TENSOR = torch.rand(1,2,3)
RAND_TENSOR


tensor([[[0.4561, 0.8049, 0.0392],
         [0.3941, 0.9171, 0.3499]]])

In [ ]:
#Zero tensors
ZERO_TENSOR = torch.zeros(3,1)
ZERO_TENSOR

tensor([[0.],
        [0.],
        [0.]])

In [ ]:
#ONES tensors
ONE_T = torch.ones(size=(3,3))
ONE_T

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#You can essentially do some masking with these:

#For eg I have my one and zero tensors. Lets multiply them and see the result
ONE_T*ZERO_TENSOR

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#Creating numbers in a range
one_ten = torch.arange(1,11)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zero_thousand_100 = torch.arange(start=0,end=1001, step=100)
zero_thousand_100

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
#Creating tensors that are LIKE other tensors
zero_like = torch.zeros_like(input=one_ten)
zero_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Float 32 tensor
float_32_TENSOR = torch.tensor([1.0])
float_32_TENSOR.dtype

torch.float32

In [ ]:
float_16_TENSOR = float_32_TENSOR.type(torch.half)
float_16_TENSOR

tensor([1.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand((2,3), dtype=torch.float16)
some_tensor

tensor([[0.2988, 0.6631, 0.6597],
        [0.1338, 0.0723, 0.9824]], dtype=torch.float16)

In [ ]:
mat1 = torch.tensor([1,2,3])
mat2 = torch.tensor([1,1,1])
print(mat1.shape)

mat3 = torch.matmul(mat1, mat2)
mat3

torch.Size([3])


tensor(6)

In [ ]:
#So for matrix mul obv the columns of the first matrix and the rows of the second matrix
# must be the same. The dimension of the resulting matrix will be the rows of the mat1 and
# columns of mat2.

#This is why:
mat1 @ mat2
# works even though the 1*3 and 1*3 matrices should technically not work.
# They work because if we do tensor.shape we get 3 for both of them therefore
# as per torch's rules they can be multiplied

#but
# torch.rand(1,2)@ torch.rand(3,2) will not work
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 3x2)

#Normal matrix multiplication works fine
t3 = torch.rand(1,2)@torch.rand(2,1)
print(t3)
t3.shape

# and the resulting shape is 1*1



tensor([[0.2950]])


torch.Size([1, 1])

In [ ]:
# Tensors of shape 3.2 and 3.2 cannot be multiplied
# but if we transpose one of them, we get 3.2 and 2.3 which should work

tensor_A = torch.tensor([[1,2],
            [1,2],
            [1,2]])

tensor_B = torch.tensor([[2,3],
            [2,3],
            [2,3]])

tensor_A

# tensor_A @ tensor_B --> this gives an error
tensor_A_transpose = tensor_A.T

tensor_A_transpose@tensor_B

# tensor.T ; the T gives us the transpose

tensor([[ 6,  9],
        [12, 18]])

In [3]:
#Tensor aggregation. Finding things like min max mean sum etc
X = torch.arange(0,100,10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
#Min:
min = X.amin()
min
max = X.amax()
max

tensor(90)

In [11]:
#mean
torch.mean(X.type(torch.float32))

tensor(45.)

In [12]:
#Sum
torch.sum(X)

tensor(450)

In [31]:
%%time
min = X.min()
min_index = (X == min).nonzero(as_tuple = True)[0]
min_index

#The above code converts tensor to a boolean tensor where only indices at which the
# value is equal to min are set to true. Next we use .nonzero() to only get the true indices
# in a tuiple since true = 1. And at last,we return the first index

CPU times: user 251 µs, sys: 8 µs, total: 259 µs
Wall time: 264 µs


tensor([0])

In [34]:
#Alternatively we can use something like arg min
min_index_arg = X.argmin()
min_index_arg

max_index = X.argmax()
max_index

tensor(9)

In [36]:
y = torch.arange(1., 10.)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
#Reshaping the tensor
y_reshaped = y.reshape(1,9) #This added an extra y dimension to our tensor
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [39]:
# y_reshaped_2 = y.reshape(2,9)
# y_reshaped_2
# This gives an error^
# we only have 9 elements so how can we make an 18 element tensor

# On the other hand we can do of shape 9*1 since we do have 9 elements
y_reshaped_2 = y.reshape(9,1)
y_reshaped_2

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [42]:
#We can reshaope a tensor in any way as long as no. of elements are not changed
ten_tensor = torch.arange(1.0, 11.0)
ten_tensor
ten_tensor_reshape = ten_tensor.reshape(5,2)
ten_tensor_reshaped_otherway = ten_tensor.reshape(2,5)
print(ten_tensor_reshape)
print(ten_tensor_reshaped_otherway)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
