<a href="https://colab.research.google.com/github/zupandit/pyTorchLearning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch

tensor = torch.rand(7,7)
tensor
# Create random tensor


tensor([[0.5783, 0.8321, 0.1359, 0.6756, 0.3550, 0.9208, 0.1273],
        [0.6015, 0.5755, 0.3073, 0.9601, 0.6847, 0.4010, 0.1132],
        [0.0969, 0.9753, 0.6277, 0.0774, 0.4148, 0.7889, 0.7383],
        [0.2524, 0.8717, 0.9276, 0.8932, 0.5791, 0.6181, 0.8816],
        [0.3217, 0.5900, 0.0496, 0.4685, 0.0658, 0.3078, 0.3344],
        [0.4852, 0.3826, 0.0417, 0.3623, 0.0819, 0.6148, 0.2643],
        [0.4352, 0.7646, 0.4361, 0.5332, 0.6134, 0.5394, 0.0140]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor_b = torch.rand(1,7)
# Perform matrix multiplication
tensor_mul = torch.matmul(tensor, tensor_b.T)
tensor_mul

tensor([[1.3809],
        [1.6258],
        [1.2240],
        [1.8443],
        [0.7765],
        [0.7974],
        [1.3382]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
tensor = torch.rand(7,7)
tensor_b = torch.rand(1,7)

# Matrix multiply tensors
print(torch.matmul(tensor, tensor_b.T))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
#


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
torch.cuda.manual_seed(RANDOM_SEED)
tensor = torch.rand(2,3, device='cuda')
torch.cuda.manual_seed(RANDOM_SEED)
tensor_b = torch.rand(2,3,device='cuda')
tensor, tensor_b

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
tensor_res = torch.matmul(tensor, tensor_b.T)
tensor_res

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
max = tensor_res.max()
# Find min
min = tensor_res.min()
max,min

(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
# Find arg max
arg_max = tensor_res.argmax()

# Find arg min
arg_min = tensor_res.argmin()
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(1,1,1,10)
print(tensor, tensor.shape)
# Remove single dimensions
print(tensor.squeeze(), tensor.squeeze().shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
